### ISSUE TITLE
How to query for content inside an array

### ISSUE THREAD

**Issue by heiglandreas** [event-engine/php-document-store#4]
Given a document inside the document store with the following content:

```json
{
  "state" : {
    "key1" : "value1",
    "key2" : [{
      "subkey" : "value 1"
    }, {
      "subkey" : "value 2"
    }],
    "key3" : "value3"
    }
}
```

How can I retrieve that document from the document store using `value 2` for `subkey` inside `key2`?

For `key1` and `key3` i'd use the following code:

```php
$filter = new EqFilter('state.key1', 'value1');
$filter = new EqFilter('state.key3', 'value3');
```

But how would I go for `value 2`?

I tried the following to no avail:

```php
$filter = new EqFilter('state.key2.subkey', 'value 1');
$filter = new EqFilter('state.key2.[].subkey', 'value 1');
```

What am I missing? Do I by chance need to use the `ArrayFilter` instead?

**Comment by codeliner** [comment]
@heiglandreas See the linked issue above for an example.

You have to use the `InArrayFilter` like this:

```php
$filter = new InArrayFilter('state.key2', ['subkey' => 'value 1']);
```
While adding tests for the filter (the repo still misses some advanced tests) I've noticed that `InArrayFilter` was not working correctly for objects in arrays (your example scenario). Fortunately, I was able to fix the issue with a small change.
